Remove coffee script and convert it to ES6
sumocoders/FrameworkExampleBundle pull request #21
Opened 2017-07-13 11:38 UTC by Katrienvh

2017-07-13 18:44 UTC, tijsverkoyen approved these changes

2017-07-17 09:10 UTC, mathiashelin approved these changes

2017-07-17 09:12 UTC, mathiashelin approved these changes

2017-07-25 09:33 UTC, tijsverkoyen commented
@Katrienvh or @mathiashelin the new coding-standards should be applied here.

2017-07-25 09:33 UTC, tijsverkoyen requested changes
@Katrienvh or @mathiashelin the new coding-standards should be applied here.

2017-08-09 09:27 UTC, tijsverkoyen approved these changes

2017-08-09 09:39 UTC, merged